"""
00a_generate_country_bbox.py - Generate country bounding boxes from Natural Earth.

Downloads Natural Earth 10m admin-0 map-units shapefile and extracts
ISO3 → [min_lon, min_lat, max_lon, max_lat] for every country/territory.
Writes result to to-rdls/configs/country_bbox.yaml.

Run once:
    cd to-rdls/notebooks
    python 00a_generate_country_bbox.py
"""

import sys
from pathlib import Path

import geopandas as gpd
import yaml

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
TORDLS_ROOT = SCRIPT_DIR.parent
CONFIGS_DIR = TORDLS_ROOT / "configs"
OUTPUT_YAML = CONFIGS_DIR / "country_bbox.yaml"

# Natural Earth 10m admin-0 map units (includes territories like Aruba, Bermuda)
NE_URL = (
    "https://naciscdn.org/naturalearth/10m/cultural/"
    "ne_10m_admin_0_map_units.zip"
)


def main():
    print("Downloading Natural Earth 10m admin-0 map units...")
    gdf = gpd.read_file(NE_URL)
    print(f"  Loaded {len(gdf)} features, columns: {sorted(gdf.columns.tolist())}")

    # Resolve ISO3 codes - ADM0_A3 is most reliable for territories
    # Fall back to ISO_A3 if ADM0_A3 is -99
    bbox_map = {}
    skipped = []

    def _merge_bbox(bmap, code, new_bb):
        """Merge bounding box into map, expanding existing if present."""
        if code in bmap:
            ex = bmap[code]
            bmap[code] = [
                round(min(ex[0], new_bb[0]), 2),
                round(min(ex[1], new_bb[1]), 2),
                round(max(ex[2], new_bb[2]), 2),
                round(max(ex[3], new_bb[3]), 2),
            ]
        else:
            bmap[code] = list(new_bb)

    # Additional ISO3 mappings for territories Natural Earth codes differently
    ne_iso3_overrides = {
        "SAH": "ESH",   # Western Sahara: ADM0_A3=SAH, should be ESH
        "SOL": "SOM",   # Somaliland: ADM0_A3=SOL, map to Somalia
        "NSV": "SJM",   # Svalbard: GU_A3=NSV, should be SJM
    }

    for _, row in gdf.iterrows():
        iso3 = str(row.get("ADM0_A3", "")).strip()
        if not iso3 or iso3 == "-99":
            iso3 = str(row.get("ISO_A3", "")).strip()
        if not iso3 or iso3 == "-99":
            iso3 = str(row.get("ISO_A3_EH", "")).strip()
        if not iso3 or iso3 == "-99" or len(iso3) != 3:
            skipped.append(row.get("NAME", "???"))
            continue

        # Apply overrides for NE-specific codes
        iso3 = ne_iso3_overrides.get(iso3, iso3)

        # Also store under ISO_A3 if different from ADM0_A3
        # (e.g., Svalbard: ADM0_A3=NOR but ISO_A3=SJM - we want both)
        alt_iso3 = str(row.get("ISO_A3_EH", "")).strip()
        if alt_iso3 and alt_iso3 != "-99" and len(alt_iso3) == 3:
            alt_iso3 = ne_iso3_overrides.get(alt_iso3, alt_iso3).upper()
        else:
            alt_iso3 = None

        iso3 = iso3.upper()
        bounds = row.geometry.bounds  # (minx, miny, maxx, maxy)
        rounded = [round(bounds[0], 2), round(bounds[1], 2),
                   round(bounds[2], 2), round(bounds[3], 2)]

        # Store/merge for primary ISO3
        _merge_bbox(bbox_map, iso3, rounded)

        # Also store under alt ISO3 if different (e.g., SJM for Svalbard)
        if alt_iso3 and alt_iso3 != iso3:
            _merge_bbox(bbox_map, alt_iso3, rounded)

    # Sort by ISO3
    sorted_bbox = dict(sorted(bbox_map.items()))

    # Write YAML
    CONFIGS_DIR.mkdir(parents=True, exist_ok=True)
    header = (
        "# Country bounding boxes from Natural Earth 10m admin-0 map units\n"
        "# Format: ISO3: [min_lon, min_lat, max_lon, max_lat] (EPSG:4326)\n"
        "# Generated by 00a_generate_country_bbox.py\n\n"
    )
    with open(OUTPUT_YAML, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("country_bbox:\n")
        for iso3, bbox in sorted_bbox.items():
            f.write(f"  {iso3}: [{bbox[0]}, {bbox[1]}, {bbox[2]}, {bbox[3]}]\n")

    print(f"\nWrote {len(sorted_bbox)} entries to {OUTPUT_YAML}")
    if skipped:
        print(f"Skipped {len(skipped)} features (no valid ISO3): {skipped[:10]}...")


if __name__ == "__main__":
    main()
