"""
00b_generate_geonames_lookup.py - Generate GeoNames country ID lookup.

Downloads the GeoNames countryInfo.txt dump and extracts
ISO3 → {geoname_id, name} for every country/territory.
Writes result to to-rdls/configs/geonames_country_ids.yaml.

Run once:
    cd to-rdls/notebooks
    python 00b_generate_geonames_lookup.py
"""

import io
from pathlib import Path

import requests
import yaml

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
TORDLS_ROOT = SCRIPT_DIR.parent
CONFIGS_DIR = TORDLS_ROOT / "configs"
OUTPUT_YAML = CONFIGS_DIR / "geonames_country_ids.yaml"

# GeoNames country info dump (tab-separated, with # comment lines)
GEONAMES_URL = "https://download.geonames.org/export/dump/countryInfo.txt"


def main():
    print("Downloading GeoNames countryInfo.txt...")
    resp = requests.get(GEONAMES_URL, timeout=60)
    resp.raise_for_status()
    text = resp.text

    # Parse TSV - skip comment lines starting with #
    # Columns (from header): ISO, ISO3, ISO-Numeric, fips, Country, Capital,
    #   Area, Population, Continent, tld, CurrencyCode, CurrencyName, Phone,
    #   Postal Code Format, Postal Code Regex, Languages, geonameId, ...
    entries = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 17:
            continue

        iso2 = parts[0].strip()
        iso3 = parts[1].strip()
        country_name = parts[4].strip()
        geoname_id_str = parts[16].strip()

        if not iso3 or len(iso3) != 3 or not geoname_id_str.isdigit():
            continue

        entries[iso3.upper()] = {
            "geoname_id": int(geoname_id_str),
            "name": country_name,
        }

    # Sort by ISO3
    sorted_entries = dict(sorted(entries.items()))

    # Write YAML
    CONFIGS_DIR.mkdir(parents=True, exist_ok=True)
    header = (
        "# GeoNames country IDs from download.geonames.org/export/dump/countryInfo.txt\n"
        "# Generated by 00b_generate_geonames_lookup.py\n\n"
    )
    with open(OUTPUT_YAML, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("geonames_country_ids:\n")
        for iso3, info in sorted_entries.items():
            # Quote name to handle special characters
            name = info["name"].replace('"', '\\"')
            f.write(f'  {iso3}:\n')
            f.write(f'    geoname_id: {info["geoname_id"]}\n')
            f.write(f'    name: "{name}"\n')

    print(f"Wrote {len(sorted_entries)} entries to {OUTPUT_YAML}")

    # Verify Aruba
    abw = sorted_entries.get("ABW")
    if abw:
        print(f"  ABW: geoname_id={abw['geoname_id']}, name={abw['name']}")


if __name__ == "__main__":
    main()
